language: node_js
node_js:
- 8.9.1
script: npm build
notifications:
  email:
    on_failure: change
    on_success: change
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist webuser@145.239.81.21:/webapps/56front
  on:
    branch: master
env:
  global:
  - REMOTE_APP_DIR=/webapps/56front
  - REMOTE_USER=webuser
  - REMOTE_HOST=145.239.81.21
  - PORT=8080
addons:
  ssh_known_hosts:
  - 145.239.81.21
before_install:
- openssl aes-256-cbc -K $encrypted_d101413217ee_key -iv $encrypted_d101413217ee_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
